### ISSUE TITLE
A question about camera trajectory file

### ISSUE THREAD

**Issue by huanzzzzz7** [vguzov/cloudrender#1]
Hello,  in the proecess of render a moving SMPL model inside a 3D scene scan, you use a camera trajectory file "TRAJ_SUB4_MPI_Etage6_working_standing.json", so  I would like to know where I can find the other camera trajectory files for the other motion scenes, or how the trajectory files were generated, since I don't see them in the HPS dataset.
Thank you so much!

**Comment by vguzov** [comment]
Hello! I'm not sure I have other trajectories available, as they were temporary files made for the video visualization purposes, but if you look inside the .json file, you can see that the structure is simple - it's just a list of position/orientation keypoints which the camera should pass, along with the time of the passing. So, the way I've generated this trajectory is just eye-balling the keypoints along with the time and trying several variants to find which works best. It's a tedious process, but any graphical 3D tool like MeshLab/Blender/etc. is usually helpful to get the proper camera position - just load pointcloud there and set the camera as you like, after that, read its position/orientation and you'll only need to guess the keypoint time now.
